import Head from 'next/head'
import Image from 'next/image'
import Tube from '../components/tube'
import State from '../components/state'
import styles from '../styles/Home.module.css'
import tubeLib from '../lib/tubes'
import stateLib from '../lib/states'

export default function Home() {

  var tubes = [
    ["1", "2", "3", "4"],
    ["5", "6", "6", "5"],
    ["7", "3", "8", "9"],
    ["8", "4", "1", "10"],
    ["3", "10", "9", "11"],
    ["12", "12", "2", "9"],
    ["8", "3", "11", "4"],
    ["7", "6", "5", "10"],
    ["9", "12", "4", "1"],
    ["11", "7", "1", "8"],
    ["6", "2", "5", "11"],
    ["12", "10", "2", "7"],
    [],
    []
  ];

  let history = [];
  history.push(tubes)

  let { stackI, stackJ } = stateLib.resolve(history)

  console.log(history)
  console.log(stackI)
  console.log(stackJ)

  let tubeExample = ['red', 'blue', 'blue', 'blue']
  let stateExample = [
    ['red', 'blue', 'blue', 'blue'],
    ['red', 'green', 'green', 'green'],
    ['green', 'red', 'blue', 'red'],
    [],
    []
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1>Ejemplo de Tubo</h1>
        <Tube colors={tubeExample} />

        <h1>Ejemplo de Estado</h1>
        <State tubes={stateExample} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
